# Site settings
title: Fjeldmann
description: "A people first software company"
url: "https://fjeldmann.dk"
baseurl: ""

# Internationalization
languages: ["da", "en"]
default_lang: "da"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Collections
collections:
  da:
    output: true
    permalink: /:name/
  en:
    output: true
    permalink: /en/:name/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Default layout
defaults:
  - scope:
      path: ""
      type: "da"
    values:
      layout: "default"
      lang: "da"
  - scope:
      path: ""
      type: "en"
    values:
      layout: "default"
      lang: "en"